import { headers } from "next/headers";
import "./globals.css";
import Header from "./header";

export const metadata = {
  title: "Akeshya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        {children}
      </body>
    </html>
  );
}
